data/urls.py
from django.conf.urls import url
from data import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addteacher', views.addteacher, name='addteacher'),
    url(r'^addsubject', views.addsubject, name='addsubject'),
    url(r'^addclassroom', views.addclassroom, name='addclassroom'),
    url(r'^addclass', views.addclass, name='addclass'),
    url(r'^view', views.view, name='view'),
    url(r'^timetable', views.timetable, name='timetable'),
]

lessons_timetabler/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as views
from data.forms import LoginForm


urlpatterns = [
    url(r'', include('data.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, {'template_name': 'data/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
]

data/models.py
from django.db import models


class Subject(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)


class Teacher(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    subject = models.ForeignKey(Subject)

    def __unicode__(self):
        return str(self.name + " " + self.surname)

    def __str__(self):
        return str(self.name + " " + self.surname)


class Class(models.Model):
    name = models.CharField(max_length=5)
    students_amount = models.IntegerField()

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)


class Classroom(models.Model):
    name = models.CharField(max_length=5)
    capacity = models.IntegerField()

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)


class Classes(models.Model):
    grade = models.CharField(max_length=5, default='')
    classes_number = models.CharField(max_length=5, default='')
    day = models.CharField(max_length=20, default='')
    room = models.CharField(max_length=50, default='')
    subject = models.CharField(max_length=50, default='')
    teacher = models.CharField(max_length=50, default='')

    def __unicode__(self):
        return str("Day: " + self.day + " Teacher: " + self.teacher + " Subject: " + self.subject +\
            " Room: " + self.room + " Classes_nr: " + self.classes_number)

    def __str__(self):
        return str("Day: " + self.day + " Teacher: " + self.teacher + " Subject: " + self.subject +\
            " Room: " + self.room + " Classes_nr: " + self.classes_number)

data/forms.py
from django import forms
from .models import Subject, Teacher, Class, Classroom, Classes
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = "__all__"


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = "__all__"


class ClassroomForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = "__all__"


class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = "__all__"

data/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core import serializers
from django.contrib.auth.decorators import login_required
from .forms import SubjectForm, TeacherForm, ClassroomForm, ClassForm, ClassesForm
from .models import Subject, Class, Teacher, Classroom, Classes
import collections


@login_required(login_url="login/")
def index(request):
    return render(request, 'data/index.html')


def view(request):
    classes = Classes.objects.order_by('grade')
    grades = Class.objects.order_by('name')
    teachers = Teacher.objects.order_by('name')
    classes_ctr_dict = collections.OrderedDict()
    __fill_dict(classes_ctr_dict)
    serialized_classes = serializers.serialize('json', classes)
    return render(request, 'data/view.html', {'classes': serialized_classes, 'grades': grades,
                                              'classes_counter': classes_ctr_dict, 'teachers': teachers})


def timetable(request):
    if request.is_ajax() and request.POST:
        post_object = Classes()
        post_object.grade = request.POST.get('grade')
        post_object.classes_number = request.POST.get('classes_number')
        post_object.day = request.POST.get('day')
        post_object.room = request.POST.get('room')
        post_object.subject = request.POST.get('subject')
        post_object.teacher = request.POST.get('teacher')
        form = ClassesForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
        return HttpResponse(post_object)
    else:
        dict = collections.OrderedDict()
        __fill_dict(dict)
        zajecia = Classes.objects.order_by('name')
        classes = Class.objects.order_by('name')
        teachers = Teacher.objects.order_by('name')
        classrooms = Classroom.objects.order_by('name')
        subjects = Subject.objects.order_by('name')
        serialized_subjects = serializers.serialize('json', subjects)
        return render(request, 'data/timetable.html',
        {'classes': classes, 'teachers': teachers, 'classrooms': classrooms,
            'classes_counter': dict, 'zajecia': zajecia, 'subjects': subjects,
            'serialized_subjects': serialized_subjects})


def addteacher(request):
    form = TeacherForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context = {
        "form": form,
    }
    return render(request, 'data/addteacher.html', context)


def addsubject(request):
    form = SubjectForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context = {
        "form": form,
    }
    return render(request, 'data/addsubject.html', context)


def addclass(request):
    form = ClassForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context = {
        "form": form,
    }
    return render(request, 'data/addclass.html', context)


def addclassroom(request):
    form = ClassroomForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context = {
        "form": form,
    }
    return render(request, 'data/addclassroom.html', context)


def __fill_dict(dict):
    dict['1'] = 1
    dict['2'] = 2
    dict['3'] = 3
    dict['4'] = 4
    dict['5'] = 5
    dict['6'] = 6
    dict['7'] = 7
    dict['8'] = 8
    dict['9'] = 9

data/templates/data/addclass.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wspomagacz planowania lekcji</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/addmodel.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Wprowadź informacje</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/#about">Start</a>
                    </li>
                    <li>
                        <a href="/#services">Usługi</a>
                    </li>
                    <li>
                        <a href="/#contact">Kontakt</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <a name="about"></a>
    <div class="container" style="top: 20%; position: relative;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default" >
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">Dodaj klasę</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post"> {% csrf_token %}
                            <p class="bs-component">
                                <table>
                                    <tr>
                                        <label for="id_name">Nazwa klasy:</label>
                                        <input id="id_name" maxlength="5" name="name" required="" type="text"><br><br>
                                    </tr>
                                    <tr>
                                        <label for="id_students_amount">Ilość uczniów:</label>
                                        <input id="id_students_amount" name="students_amount" required="" type="number"><br>
                                    </tr>
                                </table>
                            </p>
                            <p class="bs-component">
                                <center>
                                    <input class="btn btn-success btn-sm" type="submit" value="Dodaj klasę" />
                                </center>
                            </p>
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

data/templates/data/addclassroom.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wspomagacz planowania lekcji</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/addmodel.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Wprowadź informacje</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/#about">Start</a>
                    </li>
                    <li>
                        <a href="/#services">Usługi</a>
                    </li>
                    <li>
                        <a href="/#contact">Kontakt</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <a name="about"></a>
    <div class="container" style="top: 20%; position: relative;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default" >
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">Dodaj klasę</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post"> {% csrf_token %}
                            <p class="bs-component">
                                <table>
                                    <tr>
                                        <label for="id_name">Nazwa sali:</label>
                                        <input id="id_name" maxlength="5" name="name" required="" type="text"><br><br>
                                    </tr>
                                    <tr>
                                        <label for="id_capacity">Pojemność sali:</label>
                                        <input id="id_capacity" name="capacity" required="" type="number"><br>
                                    </tr>
                                </table>
                            </p>
                            <p class="bs-component">
                                <center>
                                    <input class="btn btn-success btn-sm" type="submit" value="Dodaj salę" />
                                </center>
                            </p>
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

data/templates/data/addsubject.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wspomagacz planowania lekcji</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/addmodel.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Wprowadź informacje</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/#about">Start</a>
                    </li>
                    <li>
                        <a href="/#services">Usługi</a>
                    </li>
                    <li>
                        <a href="/#contact">Kontakt</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <a name="about"></a>
    <div class="container" style="top: 20%; position: relative;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default" >
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">Dodaj klasę</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post"> {% csrf_token %}
                            <p class="bs-component">
                                <table>
                                    <tr>
                                        <label for="id_name">Nazwa przedmiotu:</label>
                                        <input id="id_name" maxlength="20" name="name" required="" type="text"><br>
                                    </tr>
                                </table>
                            </p>
                            <p class="bs-component">
                                <center>
                                    <input class="btn btn-success btn-sm" type="submit" value="Dodaj przedmiot" />
                                </center>
                            </p>
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

data/templates/data/addteacher.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wspomagacz planowania lekcji</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/addmodel.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Wprowadź informacje</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/#about">Start</a>
                    </li>
                    <li>
                        <a href="/#services">Usługi</a>
                    </li>
                    <li>
                        <a href="/#contact">Kontakt</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <a name="about"></a>
    <div class="container" style="top: 20%; position: relative;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default" >
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">Dodaj klasę</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post"> {% csrf_token %}
                            <p class="bs-component">
                                <table>
                                    <tr>
                                        <label for="id_name">Imię:</label>
                                        <input id="id_name" maxlength="20" name="name" required="" type="text"><br><br>
                                    </tr>
                                    <tr>
                                        <label for="id_surname">Nazwisko:</label>
                                        <input id="id_surname" maxlength="20" name="surname" required="" type="text"><br><br>
                                    </tr>
                                    <tr>
                                        <label for="id_subject">Przedmiot:</label>
                                        <select id="id_subject" name="subject" required="">
                                            <option value="" selected="selected">Wybierz przedmiot</option>
                                            <option value="3">Historia</option>
                                            <option value="4">Geografia</option>
                                            <option value="5">Przyroda</option>
                                            <option value="6">Plastyka</option>
                                            <option value="7">Matematyka</option>
                                            <option value="8">Język Polski</option>
                                            <option value="10">Język Angielski</option>
                                            <option value="11">Informatyka</option>
                                            <option value="12">WOS</option>
                                            <option value="13">Etyka</option>
                                        </select>
                                    </tr>
                                </table>
                            </p>
                            <p class="bs-component">
                                <center>
                                    <br><input class="btn btn-success btn-sm" type="submit" value="Dodaj przedmiot" />
                                </center>
                            </p>
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

data/templates/data/entry.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wspomagacz planowania lekcji</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>




</body>
</html>

data/templates/data/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Wspomagacz planowania lekcji</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/landing-page.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
</head>

<body>
{% block content %}
    {% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p align="center">Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container" >
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" align="center">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post"> {% csrf_token %}
                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}
</body>
</html>